In [10]:
import string

alphabet_data = [{'lower': lower, 'upper': upper, 'index':index} 
                 for lower, upper, index in zip(string.ascii_lowercase, 
                                                string.ascii_uppercase, range(1,27))]


alphabet_data

[{'lower': 'a', 'upper': 'A', 'index': 1},
 {'lower': 'b', 'upper': 'B', 'index': 2},
 {'lower': 'c', 'upper': 'C', 'index': 3},
 {'lower': 'd', 'upper': 'D', 'index': 4},
 {'lower': 'e', 'upper': 'E', 'index': 5},
 {'lower': 'f', 'upper': 'F', 'index': 6},
 {'lower': 'g', 'upper': 'G', 'index': 7},
 {'lower': 'h', 'upper': 'H', 'index': 8},
 {'lower': 'i', 'upper': 'I', 'index': 9},
 {'lower': 'j', 'upper': 'J', 'index': 10},
 {'lower': 'k', 'upper': 'K', 'index': 11},
 {'lower': 'l', 'upper': 'L', 'index': 12},
 {'lower': 'm', 'upper': 'M', 'index': 13},
 {'lower': 'n', 'upper': 'N', 'index': 14},
 {'lower': 'o', 'upper': 'O', 'index': 15},
 {'lower': 'p', 'upper': 'P', 'index': 16},
 {'lower': 'q', 'upper': 'Q', 'index': 17},
 {'lower': 'r', 'upper': 'R', 'index': 18},
 {'lower': 's', 'upper': 'S', 'index': 19},
 {'lower': 't', 'upper': 'T', 'index': 20},
 {'lower': 'u', 'upper': 'U', 'index': 21},
 {'lower': 'v', 'upper': 'V', 'index': 22},
 {'lower': 'w', 'upper': 'W', 'index': 23},
 {'lower': 'x', 'upper': 'X', 'index': 24},
 {'lower': 'y', 'upper': 'Y', 'index': 25},
 {'lower': 'z', 'upper': 'Z', 'index': 26}]

In [8]:
import pandas as pd

alphabet_pd = pd.DataFrame(alphabet_data)

In [9]:
alphabet_pd

    index lower upper
0       1     a     A
1       2     b     B
2       3     c     C
3       4     d     D
4       5     e     E
5       6     f     F
6       7     g     G
7       8     h     H
8       9     i     I
9      10     j     J
10     11     k     K
11     12     l     L
12     13     m     M
13     14     n     N
14     15     o     O
15     16     p     P
16     17     q     Q
17     18     r     R
18     19     s     S
19     20     t     T
20     21     u     U
21     22     v     V
22     23     w     W
23     24     x     X
24     25     y     Y
25     26     z     Z